name: Test Kafka connection on all envs

on:
  workflow_dispatch:
  schedule:
    - cron: '*/56 * * * *'

jobs:
  run_kafka_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test]
    continue-on-error: true

    environment: ${{ matrix.environment }}
    
    env:
      CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install confluent-kafka requests requests-oauthlib

      - name: Test Kafka functionality on ${{ matrix.environment }} env
        run: |
          ls
          chmod +x ef-health-check.py
          python3 ef-health-check.py $CREDENTIALS_JSON ${{ matrix.environment }}
        working-directory: ${{ github.workspace }}/scripts