name: Hello for All Envs

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, stage, prod]  # Define your environments here

    steps:
      - name: Say Hello
        run: echo "Hello from ${{ matrix.environment }} environment!"


